// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: books.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (
    title, 
    author, 
    flibusta_id, 
    cover_url, 
    description
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, title, author, flibusta_id, file_path, cover_url, description, created_at
`

type CreateBookParams struct {
	Title       string      `json:"title"`
	Author      pgtype.Text `json:"author"`
	FlibustaID  pgtype.Text `json:"flibusta_id"`
	CoverUrl    pgtype.Text `json:"cover_url"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook,
		arg.Title,
		arg.Author,
		arg.FlibustaID,
		arg.CoverUrl,
		arg.Description,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.FlibustaID,
		&i.FilePath,
		&i.CoverUrl,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getBookByFlibustaID = `-- name: GetBookByFlibustaID :one
SELECT id, title, author, flibusta_id, file_path, cover_url, description, created_at FROM books 
WHERE flibusta_id = $1 
LIMIT 1
`

func (q *Queries) GetBookByFlibustaID(ctx context.Context, flibustaID pgtype.Text) (Book, error) {
	row := q.db.QueryRow(ctx, getBookByFlibustaID, flibustaID)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.FlibustaID,
		&i.FilePath,
		&i.CoverUrl,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getBookByID = `-- name: GetBookByID :one
SELECT id, title, author, flibusta_id, file_path, cover_url, description, created_at FROM books 
WHERE id = $1 
LIMIT 1
`

func (q *Queries) GetBookByID(ctx context.Context, id int32) (Book, error) {
	row := q.db.QueryRow(ctx, getBookByID, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.FlibustaID,
		&i.FilePath,
		&i.CoverUrl,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT id, title, author, flibusta_id, file_path, cover_url, description, created_at FROM books 
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListBooksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBooks(ctx context.Context, arg ListBooksParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, listBooks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.FlibustaID,
			&i.FilePath,
			&i.CoverUrl,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBooks = `-- name: SearchBooks :many
SELECT id, title, author, flibusta_id, file_path, cover_url, description, created_at FROM books 
WHERE title ILIKE '%' || $1 || '%' 
   OR author ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchBooksParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) SearchBooks(ctx context.Context, arg SearchBooksParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, searchBooks, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.FlibustaID,
			&i.FilePath,
			&i.CoverUrl,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookFilePath = `-- name: UpdateBookFilePath :exec
UPDATE books 
SET file_path = $1 
WHERE id = $2
`

type UpdateBookFilePathParams struct {
	FilePath pgtype.Text `json:"file_path"`
	ID       int32       `json:"id"`
}

func (q *Queries) UpdateBookFilePath(ctx context.Context, arg UpdateBookFilePathParams) error {
	_, err := q.db.Exec(ctx, updateBookFilePath, arg.FilePath, arg.ID)
	return err
}
