// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID          int32            `json:"id"`
	Title       string           `json:"title"`
	Author      pgtype.Text      `json:"author"`
	FlibustaID  pgtype.Text      `json:"flibusta_id"`
	FilePath    pgtype.Text      `json:"file_path"`
	CoverUrl    pgtype.Text      `json:"cover_url"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID                int32            `json:"id"`
	Username          string           `json:"username"`
	Email             string           `json:"email"`
	PasswordHash      string           `json:"password_hash"`
	IsVerified        pgtype.Bool      `json:"is_verified"`
	VerificationToken pgtype.Text      `json:"verification_token"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}

type UserBook struct {
	ID              int32            `json:"id"`
	UserID          pgtype.Int4      `json:"user_id"`
	BookID          pgtype.Int4      `json:"book_id"`
	IsFavorite      pgtype.Bool      `json:"is_favorite"`
	ReadingProgress pgtype.Text      `json:"reading_progress"`
	ProgressPercent pgtype.Int4      `json:"progress_percent"`
	LastReadAt      pgtype.Timestamp `json:"last_read_at"`
}
