// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_book.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addBookToUser = `-- name: AddBookToUser :one
INSERT INTO user_books (
    user_id,
    book_id,
    is_favorite
) VALUES (
    $1, $2, $3
)
ON CONFLICT (user_id, book_id) 
DO UPDATE SET is_favorite = EXCLUDED.is_favorite
RETURNING id, user_id, book_id, is_favorite, reading_progress, progress_percent, last_read_at
`

type AddBookToUserParams struct {
	UserID     pgtype.Int4 `json:"user_id"`
	BookID     pgtype.Int4 `json:"book_id"`
	IsFavorite pgtype.Bool `json:"is_favorite"`
}

func (q *Queries) AddBookToUser(ctx context.Context, arg AddBookToUserParams) (UserBook, error) {
	row := q.db.QueryRow(ctx, addBookToUser, arg.UserID, arg.BookID, arg.IsFavorite)
	var i UserBook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.IsFavorite,
		&i.ReadingProgress,
		&i.ProgressPercent,
		&i.LastReadAt,
	)
	return i, err
}

const getUserBook = `-- name: GetUserBook :one
SELECT id, user_id, book_id, is_favorite, reading_progress, progress_percent, last_read_at FROM user_books
WHERE user_id = $1 AND book_id = $2
LIMIT 1
`

type GetUserBookParams struct {
	UserID pgtype.Int4 `json:"user_id"`
	BookID pgtype.Int4 `json:"book_id"`
}

func (q *Queries) GetUserBook(ctx context.Context, arg GetUserBookParams) (UserBook, error) {
	row := q.db.QueryRow(ctx, getUserBook, arg.UserID, arg.BookID)
	var i UserBook
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.IsFavorite,
		&i.ReadingProgress,
		&i.ProgressPercent,
		&i.LastReadAt,
	)
	return i, err
}

const getUserBooks = `-- name: GetUserBooks :many
SELECT 
    b.id,
    b.title,
    b.author,
    b.cover_url,
    ub.is_favorite,
    ub.progress_percent,
    ub.last_read_at
FROM user_books ub
JOIN books b ON b.id = ub.book_id
WHERE ub.user_id = $1
ORDER BY ub.last_read_at DESC
`

type GetUserBooksRow struct {
	ID              int32            `json:"id"`
	Title           string           `json:"title"`
	Author          pgtype.Text      `json:"author"`
	CoverUrl        pgtype.Text      `json:"cover_url"`
	IsFavorite      pgtype.Bool      `json:"is_favorite"`
	ProgressPercent pgtype.Int4      `json:"progress_percent"`
	LastReadAt      pgtype.Timestamp `json:"last_read_at"`
}

func (q *Queries) GetUserBooks(ctx context.Context, userID pgtype.Int4) ([]GetUserBooksRow, error) {
	rows, err := q.db.Query(ctx, getUserBooks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserBooksRow
	for rows.Next() {
		var i GetUserBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.CoverUrl,
			&i.IsFavorite,
			&i.ProgressPercent,
			&i.LastReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBookFromUser = `-- name: RemoveBookFromUser :exec
DELETE FROM user_books
WHERE user_id = $1 AND book_id = $2
`

type RemoveBookFromUserParams struct {
	UserID pgtype.Int4 `json:"user_id"`
	BookID pgtype.Int4 `json:"book_id"`
}

func (q *Queries) RemoveBookFromUser(ctx context.Context, arg RemoveBookFromUserParams) error {
	_, err := q.db.Exec(ctx, removeBookFromUser, arg.UserID, arg.BookID)
	return err
}

const updateReadingProgress = `-- name: UpdateReadingProgress :exec
UPDATE user_books 
SET 
    reading_progress = $1,
    progress_percent = $2,
    last_read_at = NOW()
WHERE user_id = $3 AND book_id = $4
`

type UpdateReadingProgressParams struct {
	ReadingProgress pgtype.Text `json:"reading_progress"`
	ProgressPercent pgtype.Int4 `json:"progress_percent"`
	UserID          pgtype.Int4 `json:"user_id"`
	BookID          pgtype.Int4 `json:"book_id"`
}

func (q *Queries) UpdateReadingProgress(ctx context.Context, arg UpdateReadingProgressParams) error {
	_, err := q.db.Exec(ctx, updateReadingProgress,
		arg.ReadingProgress,
		arg.ProgressPercent,
		arg.UserID,
		arg.BookID,
	)
	return err
}
