// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, email, password_hash, verification_token
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, username, email, password_hash, is_verified, verification_token, created_at
`

type CreateUserParams struct {
	Username          string      `json:"username"`
	Email             string      `json:"email"`
	PasswordHash      string      `json:"password_hash"`
	VerificationToken pgtype.Text `json:"verification_token"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.VerificationToken,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.VerificationToken,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, is_verified, verification_token, created_at FROM users 
WHERE id = $1 
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.VerificationToken,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, is_verified, verification_token, created_at FROM users 
WHERE username = $1 
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.VerificationToken,
		&i.CreatedAt,
	)
	return i, err
}

const verifyUser = `-- name: VerifyUser :one
UPDATE users 
SET is_verified = true, verification_token = NULL
WHERE verification_token = $1 
RETURNING id, username, email, password_hash, is_verified, verification_token, created_at
`

func (q *Queries) VerifyUser(ctx context.Context, verificationToken pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, verifyUser, verificationToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsVerified,
		&i.VerificationToken,
		&i.CreatedAt,
	)
	return i, err
}
